"Path","LineNumber","Line"
"D:\ChatGPT5_AI_Link\dosc\gpt5-conductor\logs\rel-20250910.jsonl","9","{""message"":""\u0027C:\\Users\\VIAD\\AppData\\Local\\Temp\\tmpA5CE.tmp\u0027 경로는 존재하지 않으므로 찾을 수 없습니다."",""action"":""changelog-pick"",""durationMs"":627,""outcome"":""failure"",""inputHash"":""efe698f13f41a0434eeffc9d85cd73d714564d8c7a07b89040715241234521b6"",""level"":""ERROR"",""timestamp"":""2025-09-10T00:39:01.698Z"",""module"":""rel"",""errorCode"":""PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand"",""traceId"":""46d69f9d3897435ab3b297dceb64264d""}"
"D:\ChatGPT5_AI_Link\dosc\gpt5-conductor\logs\rel-20250910.jsonl","19","{""message"":""\u0027C:\\Users\\VIAD\\AppData\\Local\\Temp\\tmpA5CE.tmp\u0027 경로는 존재하지 않으므로 찾을 수 없습니다."",""action"":""changelog-pick"",""durationMs"":591,""outcome"":""failure"",""inputHash"":""efe698f13f41a0434eeffc9d85cd73d714564d8c7a07b89040715241234521b6"",""level"":""ERROR"",""timestamp"":""2025-09-10T00:50:42.565Z"",""module"":""rel"",""errorCode"":""PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand"",""traceId"":""8f2ca6deda3148c5a04b2dbfe95f334e""}"
"D:\ChatGPT5_AI_Link\dosc\gpt5-conductor\logs\rel-20250910.jsonl","30","{""message"":""원격 서버에서 (422) Unprocessable Entity 오류를 반환했습니다."",""action"":""gh-create"",""durationMs"":386,""outcome"":""failure"",""inputHash"":""bc422bf60c57f0f222f30809145ed6cd763f92b2397ca9ad6d8523bf14bc0980"",""level"":""ERROR"",""timestamp"":""2025-09-10T01:04:15.778Z"",""module"":""rel"",""errorCode"":""WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand"",""traceId"":""d85a40ff00f246c0a941718d20cfb329""}"
"D:\ChatGPT5_AI_Link\dosc\gpt5-conductor\logs\release.log","1","2025-09-09 18:43:02 [ERROR] GITHUB_TOKEN�� �����ϴ�. ȯ�溯���� ���� �� ��õ��ϼ���."
"D:\ChatGPT5_AI_Link\dosc\gpt5-conductor\logs\release.log","6","2025-09-09 18:54:43 [ERROR] CHANGELOG section for version 0.1.12 not found."
"D:\ChatGPT5_AI_Link\dosc\gpt5-conductor\logs\release.log","7","2025-09-09 18:54:43 [ERROR] GITHUB_TOKEN missing. Set it and retry."
"D:\ChatGPT5_AI_Link\dosc\gpt5-conductor\logs\release.log","12","2025-09-09 18:59:25 [ERROR] CHANGELOG section for version 0.1.11 not found."
"D:\ChatGPT5_AI_Link\dosc\gpt5-conductor\logs\release.log","16","2025-09-09 18:59:25 [ERROR] CHANGELOG section for version 0.1.11 not found."
"D:\ChatGPT5_AI_Link\dosc\gpt5-conductor\logs\release.log","21","2025-09-09 19:04:36 [ERROR] CHANGELOG section for version 0.1.13 not found."
"D:\ChatGPT5_AI_Link\dosc\gpt5-conductor\logs\release.log","26","2025-09-09 19:04:36 [ERROR] CHANGELOG section for version 0.1.13 not found."
